---
apiVersion: apps/v1 # --------------------- 创建该对象所使用的 Kubernetes API 的版本
kind: Deployment # ------------------------ 对象类别：deployment
metadata:
  name: xia-nginx-deployment # ------------ deployment名字
  namespace: xia # ------------------------ 所属命令空间
  labels: # ------------------------------- 标签，( 注意区分 labels 和 namespace 的区别 )
    run: xia-nginx
spec:
  replicas: 3 # ---------------------------- pod副本数
  selector: # ----------------------------- pod选择器
    matchLabels:
      run: xia-nginx # -------------------- [ pod中的label和deployment一一对应 ] deployment所属标签，和template中的pod的标签对应表示匹配
  template: # ----------------------------- 定义 pod 模版
    metadata:
      name: xia-nginx-pod
      namespace: xia
      labels:
        run: xia-nginx # ------------------ [ pod中的label和deployment一一对应 ]
    spec:
      containers:
        - name: xia-nginx-container
          image: nginx
          imagePullPolicy: IfNotPresent # - 镜像拉取策略，IfNotPresent Never Always
          ports:
            - containerPort: 80
          volumeMounts: # ====================== 将 share-empty-volume 挂载到 nginx 容器的 /var/log/nginx 目录中
            - name: share-volume-build
              mountPath: /usr/share/nginx/html
            - name: share-volume-conf
              mountPath: /etc/nginx/conf.d
        # - name: xia-busybox-container
        #   image: busybox
        #   imagePllPolicy: Always
        #   command: ["/bin/sh", "-c", "tail -f /los/access.log"] # -- 该命令会动态的读取指定文件夹中的内容
        #   volumeMounts: # ====================== 将 share-empty-volume 挂载到 busybox 容器的 /logs 目录中
        #     - name: share-empty-volume
        #       mountPath: /logs
      volumes: # =============================== 声明 volume，name是share-empty-volume，类型是 emptyDir
        - name: share-volume-build # **************** 挂载vue打包后的文件
          # emptyDir: {} # ===================== emptyDir类型的 volume
          hostPath: # ========================== hostPath类型的 volume
            path: /root/xia/build # === Node宿主机的真实目录
            type: DirectoryOrCreate # ========== 表示目录存在就使用，不存在就先创建后使用
        - name: share-volume-conf # ***************** 挂载 nginx 配置
          hostPath:
            path: /root/xia/conf
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: xia-nginx-service
  namespace: xia
  labels:
    run: xia-nginx
spec:
  type: NodePort # NodePort 类型可以被外网访问
  selector:
    run: nginx
  ports:
    - port: 77
      targetPort: 80
